homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.buku, name='buku'),
    path('profile/', views.index, name='index'),
    path('oldProfile/', views.deijaprofile, name='deijaprofile'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
     path('main/', include('main.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.

def buku(request):
    return render(request, 'buku.html')

def index(request):
    return render(request, 'index.html')

def deijaprofile(request):
    return render(request, 'deijaprofile.html')

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

homepage/templates/DeijaProfile.html
<!DOCTYPE html>
{% load static %}

<html>

    <head>
        <title>
            Deija Profile
        </title>
        <style>
            body{
                background-color: beige;
            }
        </style>
    </head>

    <body>
        <header>
        <img src="{% static 'deijafoto.jpg' %}" style="width : 300px; height : 400px; position:absolute;top: 200px;left: 50px;">
        <img src="{% static 'makara-ui-fasilkom.png' %}" style="width : 300px; height : 300px; position:absolute;top: 250px;right: 50px;">
        <center>
            <h1>Deija Shakina Ayu</h1>
            <h3>NPM = 1906399373</h3>
            <h3>Angkatan = 2019</h3>
            <h3>Tempat Kuliah = Universitas Indonesia</h3>
            <h3>Hobi = menonton Netflix</h3>
            <br>
            <h3>Riwayat Pendidikan</h3>
            <table class="text-center" align="center">
                <tr>
                    <th>Tahun</th>
                    <th>Pendidikan</th>
                    <th>Jurusan</th>
                </tr>
                <tr>
                    <td>2005-2007</td>
                    <td>TK Perguruan Cikini</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>2007-2013</td>
                    <td>SD Perguruan Cikini</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>2013-2016</td>
                    <td>SMP Labschool Kebayoran</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>2016-2019</td>
                    <td>SMA Labschool Kebayoran</td>
                    <td>IPA</td>
                </tr>
                <tr>
                    <td>2019- sekarang</td>
                    <td>Universitas Indonesia</td>
                    <td>Fasilkom-Sistem Informasi</td>
                </tr>
            </table>
            <br>
            <h3>Sedikit Tentang Saya</h3>
            <p>Saya adalah orang yang sangat suka bercanda bersama teman.<br>
                Akhir- akhir ini sayang sedang sering-seringnya bermain<br>
                Among Us bersama teman-teman karena itu sangat menyenangkan<br>
                Saya sangat bersyukur dengan apa yang telah saya punya sekarang.
            </p>
            <br>
            <h3>Social Media</h3>
            <br>
            <div style="margin: auto; width: 200px;" align = "center">
            <a href="https://www.instagram.com/deijashakinaayu/"><img src="https://i.pinimg.com/originals/a2/5f/4f/a25f4f58938bbe61357ebca42d23866f.png" width="50" height="50"></img></a>
            <a href="https://wa.me/6287781019778"><img src="https://pngimg.com/uploads/whatsapp/whatsapp_PNG11.png" width="45" height="44"></img></a>
            <a href="https://line.me/R/ti/p/deijashakinaayu"><img src="https://1.bp.blogspot.com/-QHm3gv3zc0U/XyvL9d7C-VI/AAAAAAAACl8/OkKXjwmahkEs5E-AUt7ZGtCN1CZhjycxwCLcBGAsYHQ/s1600/Logo%2BLINE.png" width="60" height="50"></img></a>
            </div>
            <br>
        </center>
    </body>

</html>

homepage/templates/buku.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <title>Deija's Portofolio</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- My fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet"> 

    <!-- My CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <style>
    body {
        font-family:'Montserrat', sans-serif !important;
        font-size: 70px;
        font-weight: bold;
        margin: 0 30px;
    }
    .btn{
      color: black;
      background-color: transparent;
    }
    
    .text-overlay {
        position: absolute;
        top: 9em;
        left: 4.8em;
        right: 1.5em;
        font-size : 10px;
      }

    </style>
    </head>
    
    <body>

        <section class="section2">
            <div class="container">
              <div class="row">
                <div class="col-md-12" style="text-align: center">
                    <p style="margin-top: 2.5em;" class="title">HELLO</p>
                    <img class="margin-img" style="width:40%"  src="{% static 'gambar1.svg' %}">
                    <p class="title">WELCOME TO MY WEBSITE</p>
                    <div class="text-overlay">
                      <a href="{% url 'homepage:index' %}">
                        <button class="btn" style="margin-top: 22em;
                        margin-left: 15em">next</button>
                      </a>
                    </div>
                </div>
              </div>
            </div>
          </section>



    <!-- <link rel="stylessheet" href="style.css"> -->
     <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>

homepage/templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <title>Deija's Portofolio</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- My fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet"> 

    <!-- My CSS -->

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <style>
      body {
          font-family:'Montserrat', sans-serif !important;
          font-size: 15px;
          font-weight: bold;
          margin: 0 30px;
      }
      .nav-link:hover::after {
          content: '';
          display: block;
          border-bottom: 3px solid rgb(54, 54, 54);
          width: 50%;
          margin: auto;
          padding-bottom: 5px;
      
      }

      .navbar-brand{
          width: 70%;
      }

      .navbar-expand-lg .navbar-nav .nav-link {
        padding : 0 1em;
      }

      .title {
        top: 4em;
        font-size: 60px;
        font-weight: bold;
        /* border-bottom: 3px solid black; */
        /* width:50%; */
      }

      .title-2 {
        top: 5em;
        font-size: 30px;
        font-weight: bold;
        /* border-bottom: 3px solid black; */
        /* width:50%; */
      }

      .btn-2{
        color: white;
        margin-left:70em; 
        margin-top:45em; 
        background-color: black;
        border-radius: 25px;
        border-color: black;
      }

      .text-overlay {
        position: absolute;
        top: 9em;
        left: 4.8em;
        right: 1.5em;
        font-size : 10px;
      }


      .margin-gambar{
        margin-top: 2.5em;
        
      }

      .social-media{
        width: 20%;

      }



    </style>
    <!-- akhir style -->
    
    </head>
    <body>


      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <ul class="nav justify-content-center"></ul>
          <a class="navbar-brand" href="#"><img src="{% static 'logo2.png' %}" alt="logo navbar"></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
              <a class="nav-item nav-link active" href="#home-page">Home <span class="sr-only">(current)</span></a>
              <a class="nav-item nav-link" href="#about">About</a>
              <a class="nav-item nav-link" href="#education">Education</a>
              <a class="nav-item nav-link disabled" href="#contact">Contact</a>
              <a class="nav-item nav-link disabled" href="{% url 'homepage:deijaprofile' %}">Story1</a>
            </div>
          </div>
        </ul>
        </div>
      </nav>
      <!-- Akhir navbar -->

      <!-- section 1 -->
      <section class="section1" id="home-page">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <div style="text-align:center;margin-top:3em;">
                <p style="margin-top:4em" class="title">welcome :)</p>
              </div>
            </div>
            <div class="col-md-6">
              <img style="width:100%; margin-top: 3em;" src="{% static 'gambar1.jpg' %}">
              <div class="text-overlay">
                <p style="color:rgb(255, 255, 255)"><p style="color:rgb(255, 255, 255)">work portofolio<br><br><br>Hey guys, you could check-out my Profile and Check Out my<br> latest art work, hope you guys like it and if you guys are not,<br>I know why.</p></p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- akhir section 1 -->

      <!-- section 2 -->
      <section class="section2" id="about">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
                <img class="margin-img" style="width:100%; margin-top: 9em; margin-left: 10em;"  src="{% static 'about.png' %}">
                <div class="text-overlay">
                  <button class="btn-2">my work</button>
                </div>
            </div>
          </div>
        </div>
        </div>
        </section>
      </section>
      <!-- akhir sec 2 -->

      <!-- section 3  -->
      <section style="margin-top: 2em;"class="section3" id="education">
        <div class="container">
          <div class="row">
              <div class="col-md-6">
                <img style="width:100%; margin-top: 7em; margin-left:0" src="{% static 'gambar1.jpg' %}">
                </div>
                <div class="col-md-6">
                  <div style="text-align:center;margin-top: 4em;">
                    <p style="margin-top: 5em" class="title-2">Educational<br>Background<br><br></br.><img style="width:100%" src="{% static 'degree.jpg' %}"></p>
                    <div style="text-align: center;margin-top: 4em;"></div>
                  </div>
                </div>
            </div>
          </div>
      </section> 
      <!-- akhir section 3 -->

      <!-- section 4 -->
      <section class="section4" id="contact">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <div style="text-align:center; margin-top:4em">
                <p style="margin-top: 5em;" class="title">
                  Contact Me<br>
                </p>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <a href="https://www.instagram.com/deijashakina/">
              <img class="social-media" src="{% static 'ig.png' %}">
            </a>
            <a href="http://line.me/ti/p/~deijashakinaayu">
              <img class="social-media" src="{% static 'line.png' %}">
            </a>
            <a href="https://wa.me/6287781019778">
              <img style="width:14%; margin-left:1.5em" src="{% static 'whatsapp.png' %}">
            </a>
            </div>
          </div>
        </div>
      </section>
      <!-- akhir section 4 -->

    </body>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <p><img src="{% static 'img/django-logo-negative.svg' %}"></p>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
</body>
  {% block content %}
  {% endblock content %}
</html>